pipeline:
  docker:
    image: plugins/docker
    registry: registry.learnindialearn.in:5000
    username: docker
    password: yogesh12
    repo: registry.learnindialearn.in:5000/liltestingbase
    insecure: true
    auto_tag: true    
    when:
      branch: master
